spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: EXPERIAN
    password: 2064
    driver-class-name: oracle.jdbc.OracleDriver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
    consumer:
      group-id: orquestador-experian
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.poll.interval.ms: 900000

    listener:
      ack-mode: manual_immediate

  jpa:
    show-sql: true
    properties:
     hibernate:
        format_sql: true
        
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

experian:
  api:
    integracion:
        base-url: http://localhost:6001/integracion
        experian-solicitudes-url: /experian/solicitudes
        experian-descarga-documento-url: /experian/descarga-documento
    custodia:
        base-url: http://localhost:6002/custodia
        custodia-doc-url: /documento
    timeoutrequest: 15000
    timeoutresponse: 15000